# tag::pillars[]
name: Bookstore
log:
  level: debug
  format: enhanced
  output:
    type: console
db:
  enabled: true
  host: localhost
  port: 5432
  database: bookstore
  username: bookstore
  password: bookstore
  pool-size: 10
  debug: false
api:
  enabled: true
  http:
    host: 0.0.0.0
    port: 9876
    auth-token:
    max-connections: 1024
admin:
  enabled: true
  http:
    host: 0.0.0.0
    port: 19876
    max-connections: 32
observability:
  enabled: true
  service-name: bookstore
# end::pillars[]
# tag::app[]
app:
  enabled: true
  users:
    init: true
# end::app[]
