# tag::pillars[]
name: Bookstore
log:
  level: info
  format: enhanced
  output:
    type: console
db:
  host: localhost
  port: 5432
  database: bookstore
  username: postgres
  password: postgres
  pool-size: 10
  debug: false
  probe:
    timeout: PT5s
    interval: PT10s
    failure-count: 3
api:
  enabled: true
  http:
    host: 0.0.0.0
    port: 9876
    auth-token:
    max-connections: 1024
admin:
  enabled: true
  http:
    host: 0.0.0.0
    port: 19876
    max-connections: 32
observability:
  enabled: true
  service-name: bookstore
feature-flags:
  enabled: true
  flags:
    - name: feature-1
      status: enabled
    - name: feature-2
      status: disabled
# end::pillars[]
# tag::app[]
app:
  users:
    init: true
# end::app[]
