name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
env:
  GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  check-formatting:
    name: 🖼️ Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - uses: actions/cache@v3
        with:
          path: |
            .ivy2
            .sbt
          key: pillars-cache-${{ hashFiles('build.sbt', 'plugins.sbt', 'Dependencies.scala') }}
          restore-keys: |
            pillars-cache-${{ hashFiles('build.sbt', 'plugins.sbt', 'Dependencies.scala') }}
      - run: sbt scalafmtCheckAll

  test:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - uses: actions/cache@v3
        with:
          path: |
            .ivy2
            .sbt
          key: pillars-cache-${{ hashFiles('build.sbt', 'plugins.sbt', 'Dependencies.scala') }}
          restore-keys: |
            pillars-cache-${{ hashFiles('build.sbt', 'plugins.sbt', 'Dependencies.scala') }}
      - run: sbt test
