name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      DTC_HEADLESS: true
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: chmod +x dtcw
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 19
      - uses: actions/cache@v3
        with:
          path: |
            .ivy2
            .sbt
          key: pillars-cache-${{ hashFiles('build.sbt', 'plugins.sbt') }}
          restore-keys: |
            pillars-cache-${{ hashFiles('build.sbt', 'plugins.sbt') }}
      - name: generateSite
        run: ./dtcw generateSite && sbt unidoc
      - name: copyToPublic
        run: cp -r ./target/microsite/output ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: pillars.rlemaitre.com
          enable_jekyll: false
