name: Release
concurrency: Release
on:
  push:
    branches: [main]
    tags: ["v*"]
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: 📦 Install gnupg
        run: sudo apt update && sudo apt install -y gnupg

      - name: 🔑 Import PGP secret
        run: echo "${{ secrets.PGP_SECRET }}" | base64 --decode | gpg --batch --import

      - name: 📝 Update CHANGELOG
        if: ${{ github.ref_type == 'tag' }}
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

#      - name: Update version in docs
#        if: ${{ github.ref_type == 'tag' }}
#        run: |
#          TAG=${{ github.ref_name }}
#          VERSION=${TAG#v}
#          sed -i '' -e "s/\"version\": \'.*\'/\"version\": \"${VERSION}\"/" ${{ github.workspace }}/docToolchainConfig.groovy

      - name: 📦 Create Release
        if: ${{ github.ref_type == 'tag' }}
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: ✍️ Commit CHANGELOG.md
        if: ${{ github.ref_type == 'tag' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: 'CHANGELOG.md docToolchainConfig.groovy'

      - name: 👻 Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt', 'project/plugins.sbt', 'project/Dependencies.scala') }}

      - name: 📤 Publish to Sonatype
        run: sbt +test ciReleaseTagNextVersion ciReleaseSonatype
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
